SavingAlberta: MapCreator.o Map.o Character.o Game.o Driver.o
	g++ -Wall -c -std=c++0x -o SavingAlberta MapCreator.o Map.o Character.o Game.o Driver.cpp

Driver.o: Driver.cpp MapCreator.h game.h
	g++ -Wall -c -std=c++0x -o Driver.o Driver.cpp

MapCreator.o: MapCreator.cpp MapCreator.h
	g++ -Wall -c -std=c++0x -o MapCreator MapCreator.cpp

Map.o: Map.cpp Map.h
	g++ -Wall -c -std=c++0x -o Map Map.cpp

Character.o: character.cpp character.h
	g++ -Wall -c -std=c++0x -o Character character.cpp

Game.o: game.cpp game.h Map.h character.h
	g++ -Wall -c -std=c++0x -o Game game.cpp

Clean: 
	\rm *.o *~ SavingAlberta
